// Golden-fixture inputs + builder. Single source of truth for both
// gen-fixtures.mjs (writes fixtures.json) and golden.test.mjs (asserts
// against it), so the generator and the test can never drift apart.
//
// All inputs are fixed literals — no Date.now(), no randomness — so the
// output is byte-for-byte reproducible. fixtures.json doubles as the
// golden reference for the Phase 2 Rust port (ROADMAP.md).

import { buildCarousel, buildCarousels, buildFlexMessage } from '../../lib/flex-builder.js';
import { validate } from '../../lib/validate.js';

const IMG = 'https://example.com/p.jpg';

// One product per edge case; the whole array (12 = MAX_BUBBLES) is built
// with every template so each case appears under all five layouts.
export const PRODUCTS = [
  { // every field populated + money() float edge: 731.3299999 → "731.33"
    code: 'A100', name: 'วิตามินซี 1000 มก.', imageUrl: IMG,
    priceNormal: 990, priceSale: 731.3299999, promoType: 'flash',
    unitText: 'ขวด [123]', note: 'ซื้อ 2 แถม 1',
    expireText: '⏰ ถึง 14 ก.พ.', stockText: 'เหลือ 12 ชิ้น', pointsText: 'รับ 70 แต้ม',
    _promo: { type: 'percent', discount: 26, endsAt: '2025-02-14' },
  },
  { // sale price only + float edge: 26.6699999 → "26.67"; lastlot preset note
    code: 'B200', name: 'เจลล้างมือ', imageUrl: IMG,
    priceSale: 26.6699999, promoType: 'lastlot',
  },
  { // normal price only + thousand grouping: 1234567.891 → "1,234,567.89"
    code: 'C300', name: 'เครื่องวัดความดัน', imageUrl: IMG,
    priceNormal: 1234567.891, promoType: 'member',
  },
  { // no prices at all → "สอบถามราคา" / "—" paths
    code: 'D400', name: 'สินค้าสอบถามราคา', imageUrl: IMG, promoType: 'custom',
  },
  { // unknown preset falls back to custom; integer price drops ".00": "1,000"
    code: 'E500', name: 'พรีเซ็ตแปลก', imageUrl: IMG,
    priceNormal: 1000, promoType: 'weird',
  },
  { // badgeText/badgeColor overrides beat the preset values
    code: 'F600', name: 'ป้ายกำหนดเอง', imageUrl: IMG,
    priceNormal: 250, priceSale: 199, promoType: 'flash',
    badgeText: 'ลดแรง!', badgeColor: '#0A84FF',
  },
  { // money() strips one trailing zero: 26.6 → "26.6" (not "26.60")
    code: 'G700', name: 'เลขท้ายศูนย์', imageUrl: IMG,
    priceNormal: 50, priceSale: 26.6, promoType: 'flash',
  },
  { // CTA label "สนใจ รหัส LONGCODE123456" > 20 chars → sliced to 20
    code: 'LONGCODE123456', name: 'รหัสยาว', imageUrl: IMG,
    priceSale: 99, promoType: 'flash',
  },
  { // inverted prices (normal < sale) → no strike-through, no % chip, no ประหยัด
    code: 'H800', name: 'ราคากลับด้าน', imageUrl: IMG,
    priceNormal: 100, priceSale: 150, promoType: 'flash',
  },
  { // parenthesised unit cleaning: "แพ็ค (6 ชิ้น)" → "แพ็คละ"
    code: 'I900', name: 'หน่วยมีวงเล็บ', imageUrl: IMG,
    priceSale: 350, promoType: 'flash', unitText: 'แพ็ค (6 ชิ้น)',
  },
  { // http:// image → validate() error in every template
    code: 'J010', name: 'รูปไม่ปลอดภัย', imageUrl: 'http://example.com/p.jpg',
    priceSale: 75, promoType: 'flash',
  },
  { // urgent template without _promo.endsAt → plain "⏰ ด่วน! โปรหมดเร็ว" strip
    code: 'K020', name: 'ไม่มีวันหมดโปร', imageUrl: IMG,
    priceNormal: 120, priceSale: 89, promoType: 'flash', note: 'ของแถมหมดแล้วหมดเลย',
  },
];

export const TEMPLATES = ['classic', 'promo', 'bigprice', 'minimal', 'urgent'];

// 25 minimal products → buildCarousels chunks into 12 / 12 / 1.
export const CHUNK_PRODUCTS = Array.from({ length: 25 }, (_, i) => ({
  code: `C${String(i).padStart(3, '0')}`,
  name: `สินค้า ${i}`,
  imageUrl: IMG,
  priceNormal: 100 + i,
  promoType: 'flash',
}));

export function buildAll() {
  const templates = {};
  const validation = {};
  for (const t of TEMPLATES) {
    const carousel = buildCarousel(PRODUCTS, { template: t });
    templates[t] = carousel;
    validation[t] = validate(carousel);
  }

  const small = buildCarousel(PRODUCTS.slice(0, 2));

  // Hand-built bubble: 25-char footer action label → length warning.
  const longLabelCarousel = {
    type: 'carousel',
    contents: [{
      type: 'bubble',
      hero: { type: 'image', url: IMG, size: 'full', aspectRatio: '1:1', aspectMode: 'cover' },
      body: { type: 'box', layout: 'vertical', contents: [{ type: 'text', text: 'ทดสอบ label ยาว' }] },
      footer: {
        type: 'box', layout: 'vertical',
        contents: [{
          type: 'button', style: 'primary',
          action: { type: 'message', label: 'AAAAAAAAAAAAAAAAAAAAAAAAA', text: 'สนใจ' },
        }],
      },
    }],
  };

  return {
    meta: {
      note: 'Generated by test/golden/gen-fixtures.mjs — do not edit by hand. Regenerate with `npm run fixtures` and review the diff.',
    },
    cases: {
      templates,
      validation,
      chunking: buildCarousels(CHUNK_PRODUCTS),
      envelope: {
        default: buildFlexMessage(small),
        custom: buildFlexMessage(small, 'โปรเดือนนี้'),
      },
      validateEdge: {
        empty: validate({ type: 'carousel', contents: [] }),
        notCarousel: validate({}),
        longLabel: validate(longLabelCarousel),
      },
    },
  };
}
